### ISSUE TITLE
"SSE4.1 instruction set not enabled" compilation error

### ISSUE THREAD

**Issue by joyeuxnoel8** [ekg/gimbricate#3]
I ran into a similar problem as in https://github.com/vgteam/vg/issues/99
In an attempt to fix using a similar way, I added `-msse4.1` flag to the `CMAKE_CXX_FLAGS` key in my `CMakeCache.txt`
```
//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-msse4.1
```
I'm not sure if this is the proper way, but hope this might be helpful for others or future fixes.

**Comment by ekg** [comment]
Yes, this is a problem because I'm using gssw to re-derive the overlaps.

I should update this to use edlib, which I think doesn't have this
limitation.
